name: deploy template images locally, then check that their default workflow runs successfully

on:
  pull_request:
    branches:
      - main


jobs:
  deploy_image:
    runs-on: ubuntu-latest
    steps:
      steps:
        - name: Check out repository
          uses: actions/checkout@v2

        - name: Log in to GitHub Container Registry
          uses: docker/login-action@v1
          with:
            registry: ghcr.io
            username: ${{ secrets.FLYTE_BOT_USERNAME }}
            password: ${{ secrets.FLYTE_BOT_PAT }}

        - name: Iterate through top level directories and build Docker images
          run: |
            for dir in *; do
              if [ -f "$dir/{{cookiecutter.project_name}}/Dockerfile" ]; then
                echo "Building and pushing Docker image for $dir"
                docker build -f $dir/{{cookiecutter.project_name}}/Dockerfile -t local/image-${dir}:latest $dir/{{cookiecutter.project_name}}
              else
                echo "Skipping $dir as it does not contain a Dockerfile"
              fi
            done
